sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov --use-mirrors
  - pip install coveralls --use-mirrors
  #- pip install pytest  # installed by Travis by default already
script:
  - py.test --cov pygar_me
after_success:
  - coveralls
